# Generated by Django 4.1.7 on 2023-04-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_orders_client_alter_orders_date_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
    ]
