# Generated by Django 4.1.7 on 2023-04-10 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_orders_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksorder',
            name='completed',
            field=models.CharField(default='Не определено', max_length=30, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='worksorder',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая сумма'),
        ),
        migrations.AlterField(
            model_name='worksorder',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наименование работы'),
        ),
        migrations.AlterField(
            model_name='worksorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.orders', verbose_name='Выбор з/наряда'),
        ),
        migrations.AlterField(
            model_name='worksorder',
            name='order_status',
            field=models.CharField(default='Согласование', max_length=20, verbose_name='Статус работы'),
        ),
        migrations.AlterField(
            model_name='worksorder',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость н/ч'),
        ),
        migrations.AlterField(
            model_name='worksorder',
            name='standard',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Норма времени н/ч'),
        ),
    ]
