# Generated by Django 4.1.7 on 2023-04-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_worksorder_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая стоимость наряда'),
        ),
        migrations.AlterField(
            model_name='worksorder',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая стоимость работы'),
        ),
    ]
