# Generated by Django 4.1.7 on 2023-05-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depositary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Артикул детали')),
                ('part_name', models.CharField(max_length=300, verbose_name='Название детали')),
                ('part_location', models.CharField(max_length=50, verbose_name='Расположение детали')),
                ('input_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Входная стоимость')),
                ('output_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Входная стоимость')),
                ('markup_cost', models.DecimalField(decimal_places=2, default=5, max_digits=10, verbose_name='Наценка %')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество, шт.')),
            ],
        ),
    ]
