# Generated by Django 4.1.7 on 2023-05-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_worksorder_executor'),
        ('depositary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depositary',
            options={'ordering': ['part_name']},
        ),
        migrations.AddField(
            model_name='depositary',
            name='date_closing',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия'),
        ),
        migrations.AddField(
            model_name='depositary',
            name='date_opening',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата поступления'),
        ),
        migrations.AddField(
            model_name='depositary',
            name='order',
            field=models.ManyToManyField(blank=True, to='service.orders', verbose_name='Принадлежность к наряду'),
        ),
        migrations.AlterField(
            model_name='depositary',
            name='output_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Выходная стоимость'),
        ),
    ]
