# Generated by Django 4.1.7 on 2023-06-16 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depositary', '0003_remove_depositary_order_depositary_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depositary',
            options={'ordering': ['-id']},
        ),
    ]
