# Generated by Django 4.1.7 on 2023-04-16 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('time', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Выработка н/ч')),
                ('jod_title', models.CharField(choices=[(1, 'Мастер'), (2, 'Механик')], default=2, max_length=20, verbose_name='Должность')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата трудоустройства')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
