# Generated by Django 4.1.7 on 2023-04-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_person_jod_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='jod_title',
            field=models.CharField(default='Механик', max_length=20, verbose_name='Должность'),
        ),
    ]
